// Auto-generated by convert-images.js
// This file provides utilities for using optimized images

import imageManifest from './image-manifest.json';

const CDN_BASE = 'https://cdn.jsdelivr.net/gh/YOUR_USERNAME/YOUR_REPO@main/optimized-images';

/**
 * Get optimized image URL for a given original path
 * @param {string} originalPath - Original image path (e.g., 'LandingPage/bg_image.png')
 * @param {number} [width] - Desired width, or undefined for full size
 * @returns {string} Optimized CDN URL
 */
export function getOptimizedUrl(originalPath, width) {
  const entry = imageManifest[originalPath];
  if (!entry) {
    console.warn(`Image not found in manifest: ${originalPath}`);
    return originalPath;
  }
  
  if (width) {
    // Find the closest width that's >= requested width
    const availableWidths = Object.keys(entry.webp)
      .filter(k => k.endsWith('w'))
      .map(k => parseInt(k))
      .sort((a, b) => a - b);
    
    const bestWidth = availableWidths.find(w => w >= width) || 'full';
    const key = bestWidth === 'full' ? 'full' : `${bestWidth}w`;
    return `${CDN_BASE}/${entry.webp[key].path}`;
  }
  
  return `${CDN_BASE}/${entry.webp.full.path}`;
}

/**
 * Generate srcSet string for responsive images
 * @param {string} originalPath - Original image path
 * @returns {{ src: string, srcSet: string, sizes: string }}
 */
export function getSrcSet(originalPath) {
  const entry = imageManifest[originalPath];
  if (!entry) {
    return { src: originalPath, srcSet: '', sizes: '' };
  }
  
  const srcSetParts = [];
  let largestWidth = 0;
  let largestPath = '';
  
  for (const [key, data] of Object.entries(entry.webp)) {
    const url = `${CDN_BASE}/${data.path}`;
    
    if (key === 'full') {
      srcSetParts.push(`${url} ${data.width}w`);
      if (data.width > largestWidth) {
        largestWidth = data.width;
        largestPath = url;
      }
    } else if (key.endsWith('w')) {
      srcSetParts.push(`${url} ${data.width}w`);
      if (data.width > largestWidth) {
        largestWidth = data.width;
        largestPath = url;
      }
    }
  }
  
  return {
    src: largestPath,
    srcSet: srcSetParts.join(', '),
    sizes: '(max-width: 600px) 480px, (max-width: 1200px) 960px, 1440px',
  };
}

export { imageManifest };
